Introducing Module Decorator for Enhanced IoC and Context Management (#18)
* Module decorator: IOC : app_context

* fix bad import

* fix tests

* fix - ImportError: cannot import name 'async_db_request_handler' from 'nest.core.decorators'

modify blank app example to work with module decorator

* modify blank app example to work with module decorator

* Introduce @HttpCode decorator for specifying HTTP response status

* Enhance route decorators to allow default path values using a generic @route decorator

* Add type annotations in specific parts

* renaming  related_mod to compiled_related_module

* fixing bad import for HttpCode decorator

* fixing PyNestContainer) -> Module circular import

* fixing PyNestContainer) -> Module circular import

* fixing PyNestContainer) -> Module circular import

* Type hints added to refactored HTTP methods

* Feature: Multiple paths for controller's methods

* Fix test failures in test_core/test_decorators/test_controller.py

* run black

* change examples to work with the new module decorator and the new application file structure

* make cli g module add new module created to app module

* fix:

nest.common.exceptions.NoneInjectableException

* fix: response 500

* fix: config is not defined

* fix tests
revert controller to 0.1.2 version
rename helper in decorators
run black on project

* modified documentations to show the new way for creating modules and applications.
remove test app, app file
modified existing redis module from plugins

* add documentation to pynest_app_context.py
modified redis module to work with the new architecture
add test to pynest factory

* run black

* Add working dependency injection system to pynest

* fix ImportError: cannot import name 'run_nest_app'

* fix E   ModuleNotFoundError: No module named 'injector'

* fix Exception: orm_config.py file not found

* fix pydantic 2 error, fix app_module import error

* fix ERROR:    Error loading ASGI app. Could not import module "app".

* fix app.py does not exist in AsyncORMApp.

* fix integration test

* fix integration test

* fix integration test

* fix integration test

* fix integration test

* fix integration test

* fix config path

* fix integreation test

* fix integreation test

* fix integreation test

* fix integreation test
run isort
run black

* fix controller docs file

---------

Co-authored-by: ItayTheDar <itda@post.bgu.ac.il>